apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: pipelines-vote-ui
  name: pipelines-vote-ui
spec:
  selector:
    name: pipelines-vote-ui
  template: 
    metadata:
      labels:
        name: "pipelines-vote-ui"
    spec:
      containers:
        - image: quay.io/openshift-pipeline/vote-ui:latest
          imagePullPolicy: Always
          name: pipelines-vote-ui
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
          env:
            - name: VOTING_API_SERVICE_HOST
              value: pipelines-vote-api
            - name: VOTING_API_SERVICE_PORT
              value: "9000"
  replicas: 2
  strategy: 
    type: "Rolling"
  paused: false 
  revisionHistoryLimit: 2 
  minReadySeconds: 0 
